version: '3'

services:
  mongo_db:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=crude_graphql
    volumes:
      - ./mgdata:/data/db

  api:
    build: .
    restart: always
    container_name: node
    ports:
      - 3333:3333
    volumes:
      - .:/usr/api
    depends_on:
      - mongo_db
